[Variables]
skin.width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
skin.height=100
key=#SKINSPATH#Droptop\@Resources\GlobalVar\UserSettings.inc
CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#
RoundTo=1
key2=#SKINSPATH#Droptop Community Apps\Apps\Droptop_Theme_Changer-Mike_Boynton\Variables\Variables.inc
CurrentTheme=[#ThemeName15] Theme
